# Generated by Django 4.0.5 on 2022-06-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=30)),
                ('comision_curso', models.IntegerField()),
                ('cantidad_maxima_de_personas_curso', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_evento', models.CharField(max_length=30)),
                ('lugar_evento', models.CharField(max_length=60)),
                ('descripcion_evento', models.CharField(max_length=150)),
                ('incio_evento', models.DateTimeField()),
                ('fin_evento', models.DateTimeField()),
            ],
        ),
    ]
